# Generated by Django 3.2.7 on 2021-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KEGG_PATHWAY_MODEL',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='map number')),
                ('desc', models.CharField(max_length=255, verbose_name='map description')),
                ('image', models.ImageField(upload_to='', verbose_name='map image file')),
                ('conf', models.FileField(upload_to='', verbose_name='map config file')),
            ],
        ),
    ]
